import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { RootState, useAppDispatch, useAppSelector } from '@/store';
import { resetSelectedObj } from '@/store/slice/selectedObjSlice';
import Controls from '@/components/Wrapper/controls';
import { Spinner } from '@/components/ui/spinner';
import { Label } from '@/components/ui';
import { getPayslipDetails } from '../service';
import PAYSLIP_CONSTANTS from '../constants';

interface ViewProps {}

const PayslipViewController: React.FC<ViewProps> = ({}) => {
  const { [PAYSLIP_CONSTANTS.ENTITY_KEY]: { showView, primaryKeys } = {} } = useAppSelector((state: RootState) => state.selectedObj);
  const dispatch = useAppDispatch();

  const { data: payslip, isLoading } = useQuery({
    queryKey: [PAYSLIP_CONSTANTS.QUERY_KEY, primaryKeys, primaryKeys?.payslipId, showView],
    queryFn: () => getPayslipDetails(primaryKeys?.payslipId || 0),
    enabled: Boolean(showView && primaryKeys?.payslipId),
  });

  const handleClose = React.useCallback(() => {
    dispatch(resetSelectedObj(PAYSLIP_CONSTANTS.ENTITY_KEY));
  }, [dispatch]);

  const Content = () => (
    <>
      {isLoading && (
        <div className="flex items-center justify-center py-10 h-1/2">
          <Spinner />
        </div>
      )}
      {!isLoading && payslip && (
        <div className="grid grid-cols-1 gap-6 items-start">
        <div className="space-y-2">
          <Label>Payslip Id</Label>
          <div className="flex items-center text-sm bg-muted p-3 rounded-md">{payslip?.data?.payslipId ?? '-'}</div>
        </div>
        <div className="space-y-2">
          <Label>Employee Id</Label>
          <div className="flex items-center text-sm bg-muted p-3 rounded-md">{payslip?.data?.employeeId ?? '-'}</div>
        </div>
        <div className="space-y-2">
          <Label>Pay Period Start</Label>
          <div className="flex items-center text-sm bg-muted p-3 rounded-md">{payslip?.data?.payPeriodStart ? new Date(payslip?.data?.payPeriodStart).toLocaleDateString() : '-'}</div>
        </div>
        <div className="space-y-2">
          <Label>Pay Period End</Label>
          <div className="flex items-center text-sm bg-muted p-3 rounded-md">{payslip?.data?.payPeriodEnd ? new Date(payslip?.data?.payPeriodEnd).toLocaleDateString() : '-'}</div>
        </div>
        <div className="space-y-2">
          <Label>Gross Salary</Label>
          <div className="flex items-center text-sm bg-muted p-3 rounded-md">{payslip?.data?.grossSalary ?? '-'}</div>
        </div>
        <div className="space-y-2">
          <Label>Net Salary</Label>
          <div className="flex items-center text-sm bg-muted p-3 rounded-md">{payslip?.data?.netSalary ?? '-'}</div>
        </div>
        <div className="space-y-2">
          <Label>Deductions Amount</Label>
          <div className="flex items-center text-sm bg-muted p-3 rounded-md">{payslip?.data?.deductionsAmount ?? '-'}</div>
        </div>
        <div className="space-y-2">
          <Label>Allowances Amount</Label>
          <div className="flex items-center text-sm bg-muted p-3 rounded-md">{payslip?.data?.allowancesAmount ?? '-'}</div>
        </div>
        <div className="space-y-2">
          <Label>Pdf Url</Label>
          <div className="flex items-center text-sm bg-muted p-3 rounded-md">{payslip?.data?.pdfUrl ?? '-'}</div>
        </div>
        <div className="space-y-2">
          <Label>Generated By</Label>
          <div className="flex items-center text-sm bg-muted p-3 rounded-md">{payslip?.data?.generatedBy ?? '-'}</div>
        </div>
        <div className="space-y-2">
          <Label>Created At</Label>
          <div className="flex items-center text-sm bg-muted p-3 rounded-md">{payslip?.data?.createdAt ? new Date(payslip?.data?.createdAt).toLocaleDateString() : '-'}</div>
        </div>
        <div className="space-y-2">
          <Label>Updated At</Label>
          <div className="flex items-center text-sm bg-muted p-3 rounded-md">{payslip?.data?.updatedAt ? new Date(payslip?.data?.updatedAt).toLocaleDateString() : '-'}</div>
        </div>
        </div>
      )}
    </>
  );

  return (
    <Controls
      title={`${PAYSLIP_CONSTANTS.ENTITY_NAME} Details`}
      open={showView}
      onClose={handleClose}
      type="modal"
      width={800}
      loading={isLoading}
    >
      <Content />
    </Controls>
  );
};

export default PayslipViewController;